#Import the Client package from Twilio Libary
from twilio.rest import Client
from time import sleep
from random import randint
import filtering_text
import amount

#Set account Sid and authentication token which was generated by Twilio
account_sid = 'AC8089675596c4cf82d6a935da9e7d301e'
auth_token = '136f309ae341a49a6711587f73af0948'
client = Client(account_sid, auth_token)

#numbers_to_message = ['+15558675310', '+14158141829', '+15017122661']
#for number in numbers_to_message:
#numbers_to_message = ['+2348156625870', '+2348163891244', '']
#payment_list = [ '1ksh', '2ksh', '5ksh', '10ksh', '20ksh']


name = filtering_text.message_output
timer = filtering_text.time_output
amounts = amount.c
mins = amount.mins
smsCode = str(randint(100000, 999999))
message = client.messages \
    .create(
         
         body='Hi ' +str(name) + ' you have sent us ' + str(amounts) + " at " + str(timer) + ' You have ' +str(mins) + ' Your verification code is ' + smsCode + ' , Please wait three minutes to get the system activated',
         from_='+13866434696', #Number generated by Twilio
         to='+2348156625870' #Specify the number to send to which must be added in verified numbers on Twilio
     )


#Displays status of the file and file attributes 
print(message.sid)
print(message.status)

